### ISSUE TITLE
不晓得为啥，运行后会提示json有问题

### ISSUE THREAD

**Issue by raphaelxiao** [yiyuezhuo/National-Data#2]
如下（日期改为了1978-2023）

Traceback (most recent call last):
  File "C:\Users\Raphael\.conda\envs\NBS_data\Lib\site-packages\requests\models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Raphael\.conda\envs\NBS_data\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Raphael\.conda\envs\NBS_data\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Raphael\.conda\envs\NBS_data\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Raphael\Desktop\Developer\NBS_data\National-Data\main.py", line 294, in <module>
    CLI()
  File "C:\Users\Raphael\Desktop\Developer\NBS_data\National-Data\main.py", line 271, in CLI
    run(args)
  File "C:\Users\Raphael\Desktop\Developer\NBS_data\National-Data\main.py", line 241, in run
    tree.get_recur()
  File "C:\Users\Raphael\Desktop\Developer\NBS_data\National-Data\main.py", line 61, in get_recur
    self.get(verbose=verbose)
  File "C:\Users\Raphael\Desktop\Developer\NBS_data\National-Data\main.py", line 54, in get
    self.data=res.json()
              ^^^^^^^^^^
  File "C:\Users\Raphael\.conda\envs\NBS_data\Lib\site-packages\requests\models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by javachens** [comment]
一样的问题，解决了吗？
